name: Openfabric Testnet Test workflow

on: workflow_dispatch

jobs:
  run-tests:

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

#    - name: Cache dependencies
#      id: cache
#      uses: actions/cache@v3
#      with:
#        path: |
#          venv
#          ~/.cache/pip
#        key: ${{ runner.os }}-python-${{ hashFiles('requirements.txt') }}
#        restore-keys: |
#          ${{ runner.os }}-python-

#    - name: Set up Python 3.11
#      uses: actions/setup-python@v3
#      with:
#        python-version: "3.11.7"
#        cache: 'pip'

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: 10406996

    - name: run emulator
      run: |
        cd /Users
        dir
        

#    - name: Set up Node js
#      uses: actions/setup-node@v4
#      with:
#        node-version: 20
#
#    - name: Install Appium
#      run: npm install -g appium
#
#    - name: Install Appium animator
#      run: appium driver install uiautomator2
#
#    - name: Start Appium Server
#      run: appium &>/dev/null &

#    - name: Install appium driver
#      run: appium driver install uiautomator2

#    - name: Setup virtual environment
#      run: |
#
#    - name: Install dependencies
#      run: |


#    - name: run tests
#      uses: reactivecircus/android-emulator-runner@v2
#      with:
#        api-level: 29
#        script: |
#          python -m venv venv
#          source venv/bin/activate
#          pip install --upgrade pip
#          pip install -r requirements.txt
#          python setup_appium.py
#    - name: Send CSV data to slack
#      run: python slack_app/send_test_reports.py
